# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: leo
  password: 123456
  pool: 5

development:
  <<: *default
  database: app

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
